color: purple
fieldLayouts:
  aa98138f-4bb9-484f-a29a-12a32b676aa4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T13:40:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9dc3ef68-3363-478d-8f72-88301ae946a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 67711461-a324-4f72-b0ef-62ea12aa0874
        userCondition: null
handle: contact
hasTitleField: true
icon: at
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: language
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: language
