color: orange
fieldLayouts:
  9263a9b4-2530-4096-8c49-56669ab7884b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T13:27:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4381831b-c7c2-4382-957b-b8984ab575fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-06T13:31:11+00:00'
            elementCondition: null
            fieldUid: 6215174c-f9ad-4cce-a65b-7cc29d7a4df7 # Entry Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4235758a-f008-4c11-8b7a-61ab1661ae5f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-06T13:31:11+00:00'
            elementCondition: null
            fieldUid: 8545091e-6aa2-47f7-b003-14e7d1191c06 # Site Entry
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cff4d21-1377-4e3b-a275-3638baa9c7ed
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 24bc66a1-c9c5-46c3-9f22-8e92423d081c
        userCondition: null
handle: entry
hasTitleField: false
icon: link
name: Entry
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
