color: purple
fieldLayouts:
  169bb755-e8f7-405b-ad8c-6777be95b383:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T13:37:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc7e1d38-7663-4801-80e9-f56f66972697
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c5472f8-3746-4c9e-910a-39ba657b8359
        userCondition: null
handle: projects
hasTitleField: true
icon: dog
name: Projects
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: language
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: language
