columnSuffix: null
handle: mainSection
instructions: null
name: 'Main Section'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 6ba47df5-668b-4d19-9c77-a2074bf06501 # Media Container
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
