columnSuffix: null
handle: mediaWidth
instructions: null
name: 'Media Width'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 20%
        -
          - value
          - '20'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 25%
        -
          - value
          - '25'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 30%
        -
          - value
          - '30'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 35%
        -
          - value
          - '35'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 40%
        -
          - value
          - '40'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 45%
        -
          - value
          - '45'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 50%
        -
          - value
          - '50'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 55%
        -
          - value
          - '55'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 60%
        -
          - value
          - '60'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 65%
        -
          - value
          - '65'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 70%
        -
          - value
          - '70'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 75%
        -
          - value
          - '75'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 80%
        -
          - value
          - '80'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 85%
        -
          - value
          - '85'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 90%
        -
          - value
          - '90'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 95%
        -
          - value
          - '95'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 100%
        -
          - value
          - '100'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
