columnSuffix: null
handle: mediaSelection
instructions: null
name: 'Media Selection'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Image
        -
          - value
          - image
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Video
        -
          - value
          - video
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
