columnSuffix: null
handle: year
instructions: null
name: Year
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1995
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: 4
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
