defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2427c74a-4636-4918-b5b7-f02d51d963d0 # Projects
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a5a21d6c-2f1e-4127-86f3-07b2581978f6: # Ojo de Agua
    enabledByDefault: true
    hasUrls: true
    template: _/pages/projects.twig
    uriFormat: proyectos
  df4ba043-3c09-479f-9650-70512a4c3ec8: # Ojo de Agua - EN
    enabledByDefault: true
    hasUrls: true
    template: _/pages/projects.twig
    uriFormat: projects
type: single
